DEFAULT_CONFIG_PATH = "tests/default_config.yml"
BENCHMARK_CONFIG_PATH = "tests/benchmarks/benchmark_config.yml"
SIMULATION_SCRIPT = "src/quvac/simulation.py"
GRIDSCAN_SCRIPT = "src/quvac/cluster/gridscan.py"
OPTIMIZATION_SCRIPT = "src/quvac/cluster/optimization.py"
